import {
  Mombasa,
  lakenakuru,
  luwenzori,
  mountKenya1,
  nature2,
  nature3,
} from "../assets";

export const destinations = [
  {
    image: mountKenya1,
    siteName: "Mount Kenya",
    alt: "image of mountb kenya",
    description: "Second largest mountain in Africa.",
    linkText: "Read More",
    pricePerGroup: "Kshs 5,000",
    individualCost: "Kshs 5,500",
  },
  {
    image: luwenzori,
    siteName: "Aberdare Hill",
    alt: " image of aberdare range",
    description: "A heritage destination for central Kenya",
    linkText: "Read More",
    pricePerGroup: "Kshs 3,500",
    individualCost: "Kshs 4,000",
  },
  {
    image: nature3,
    siteName: "Indian Ocean",
    alt: "Image of indian ocean",
    description: "One of the worlds largest oceans in the world",
    linkText: "Read More",
    pricePerGroup: "Kshs 5,000",
    individualCost: "Kshs 5,400",
  },
  {
    image: nature2,
    siteName: "Tsavo National Park",
    alt: "image of hot air ballon in Tsavo",
    description: "A seamless outdoor exploration and time of fun",
    linkText: "Read More",
    pricePerGroup: "Kshs 2,000",
    individualCost: "Kshs 2,200",
  },
  {
    image: Mombasa,
    siteName: "Mombasa Island",
    alt: "Image of Mombasa Island",
    description: "The city within an island",
    linkText: "Read More",
    pricePerGroup: "Kshs 1,800",
    individualCost: "Kshs 2,000",
  },
  {
    image: lakenakuru,
    siteName: "Lake Nakuru",
    alt: "image of lake nakuru ",
    description: "A heritage for Kenya and a home for the worlds Flamingos",
    linkText: "Read More",
    pricePerGroup: "Kshs 4,000",
    individualCost: "Kshs 4,400",
  },
];

export const sites = [
  {
    image: mountKenya1,
    siteName: "Mount Kenya",
    alt: "image of mountb kenya",
    description: "Second largest mountain in Africa.",
    linkText: "Read More",
    pricePerGroup: "Kshs 5,000",
    individualCost: "Kshs 5,500",
  },
  {
    image: luwenzori,
    siteName: "Aberdare Hill",
    alt: " image of aberdare range",
    description: "A heritage destination for central Kenya",
    linkText: "Read More",
    pricePerGroup: "Kshs 3,500",
    individualCost: "Kshs 4,000",
  },
  {
    image: nature3,
    siteName: "Indian Ocean",
    alt: "Image of indian ocean",
    description: "One of the worlds largest oceans in the world",
    linkText: "Read More",
    pricePerGroup: "Kshs 5,000",
    individualCost: "Kshs 5,400",
  },
  {
    image: nature2,
    siteName: "Tsavo National Park",
    alt: "image of hot air ballon in Tsavo",
    description: "A seamless outdoor exploration and time of fun",
    linkText: "Read More",
    pricePerGroup: "Kshs 2,000",
    individualCost: "Kshs 2,200",
  },
  {
    image: Mombasa,
    siteName: "Mombasa Island",
    alt: "Image of Mombasa Island",
    description: "The city within an island",
    linkText: "Read More",
    pricePerGroup: "Kshs 1,800",
    individualCost: "Kshs 2,000",
  },
  {
    image: lakenakuru,
    siteName: "Lake Nakuru",
    alt: "image of lake nakuru ",
    description: "A heritage for Kenya and a home for the worlds Flamingos",
    linkText: "Read More",
    pricePerGroup: "Kshs 4,000",
    individualCost: "Kshs 4,400",
  },
  {
    image: nature3,
    siteName: "Indian Ocean",
    alt: "Image of indian ocean",
    description: "One of the worlds largest oceans in the world",
    linkText: "Read More",
    pricePerGroup: "Kshs 5,000",
    individualCost: "Kshs 5,400",
  },
  {
    image: nature2,
    siteName: "Tsavo National Park",
    alt: "image of hot air ballon in Tsavo",
    description: "A seamless outdoor exploration and time of fun",
    linkText: "Read More",
    pricePerGroup: "Kshs 2,000",
    individualCost: "Kshs 2,200",
  },
];
