import {
    adventure,
    coast1,
    culinary,
    culture,
    ecotours,
    family,
    honeymoon,
    luxurytours,
    wellness,
    Tsavo,
  } from "../assets";
  
  export const packages = [
    {
      image: honeymoon,
      type: "Honey Moon",
      alt: "image of a honey moon",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 5,000",
      oldPrice:"Kshs 5,500",
    },
    {
      image: family,
      type: "Family",
      alt: " image of aberdare range",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 3,500",
      oldPrice:"Kshs 4,000",
    },
    {
      image: adventure,
      type: "Adventure",
      alt: "Image of indian ocean",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 5,000",
      oldPrice:"Kshs 5,400",
    },
    {
      image: culture,
      type: "Cultural Tours",
      alt: "image of hot air ballon in Tsavo",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 2,000",
      oldPrice:"Kshs 2,600",
    },
    {
      image: Tsavo,
      type: "Wildlife Safaris",
      alt: "Image of Mombasa Island",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 1,800",
      oldPrice:"Kshs 2,000",
    },
    {
      image: ecotours,
      type: "Eco-tours",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,500",
    },
    {
      image: luxurytours,
      type: "Luxury vacations",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,200",
    },
    {
      image: coast1,
      type: "Beach holidays",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,300",
    },
    {
      image: wellness,
      type: "wellness retreats",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,400",
    },
    {
      image: culinary,
      type: "Culinary tours",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,400",
      oldPrice:"Kshs 5,000",
    },
  ];