import {
    Mombasa,
    lakenakuru,
    luwenzori,
    mountKenya1,
    nature2,
    nature3,
  } from "../assets";
  
  export const packages = [
    {
      image: mountKenya1,
      type: "Honey Moon",
      alt: "image of mount kenya",
      description: "Second largest mountain in Africa.",
      linkText: "Read More",
      price: "Kshs 5,000",
    },
    {
      image: luwenzori,
      type: "Family",
      alt: " image of aberdare range",
      description: "A heritage destination for central Kenya",
      linkText: "Read More",
      price: "Kshs 3,500",
    },
    {
      image: nature3,
      type: "Adventure",
      alt: "Image of indian ocean",
      description: "One of the worlds largest oceans in the world",
      linkText: "Read More",
      price: "Kshs 5,000",
    },
    {
      image: nature2,
      type: "Cultural Tours",
      alt: "image of hot air ballon in Tsavo",
      description: "A seamless outdoor exploration and time of fun",
      linkText: "Read More",
      price: "Kshs 2,000",
    },
    {
      image: Mombasa,
      type: "Wildlife Safaris",
      alt: "Image of Mombasa Island",
      description: "The city within an island",
      linkText: "Read More",
      price: "Kshs 1,800",
    },
    {
      image: lakenakuru,
      type: "Eco-tours",
      alt: "image of lake nakuru ",
      description: "A heritage for Kenya and a home for the worlds Flamingos",
      linkText: "Read More",
      price: "Kshs 4,000",
    },
    {
      image: lakenakuru,
      type: "Luxury vacations",
      alt: "image of lake nakuru ",
      description: "A heritage for Kenya and a home for the worlds Flamingos",
      linkText: "Read More",
      price: "Kshs 4,000",
    },
    {
      image: lakenakuru,
      type: "Beach holidays",
      alt: "image of lake nakuru ",
      description: "A heritage for Kenya and a home for the worlds Flamingos",
      linkText: "Read More",
      price: "Kshs 4,000",
    },
    {
      image: lakenakuru,
      type: "wellness retreats",
      alt: "image of lake nakuru ",
      description: "A heritage for Kenya and a home for the worlds Flamingos",
      linkText: "Read More",
      price: "Kshs 4,000",
    },
    {
      image: lakenakuru,
      type: "Culinary tours",
      alt: "image of lake nakuru ",
      description: "A heritage for Kenya and a home for the worlds Flamingos",
      linkText: "Read More",
      price: "Kshs 4,400",
    },
  ];