import {
    Mombasa,
    lakenakuru,
    luwenzori,
    mountKenya1,
    nature2,
    nature3,
  } from "../assets";
  
  export const packages = [
    {
      image: mountKenya1,
      type: "Honey Moon",
      alt: "image of mount kenya",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 5,000",
      oldPrice:"Kshs 5,500",
    },
    {
      image: luwenzori,
      type: "Family",
      alt: " image of aberdare range",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 3,500",
      oldPrice:"Kshs 4,000",
    },
    {
      image: nature3,
      type: "Adventure",
      alt: "Image of indian ocean",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 5,000",
      oldPrice:"Kshs 5,400",
    },
    {
      image: nature2,
      type: "Cultural Tours",
      alt: "image of hot air ballon in Tsavo",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 2,000",
      oldPrice:"Kshs 2,600",
    },
    {
      image: Mombasa,
      type: "Wildlife Safaris",
      alt: "Image of Mombasa Island",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 1,800",
      oldPrice:"Kshs 2,000",
    },
    {
      image: lakenakuru,
      type: "Eco-tours",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,500",
    },
    {
      image: lakenakuru,
      type: "Luxury vacations",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,200",
    },
    {
      image: lakenakuru,
      type: "Beach holidays",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,300",
    },
    {
      image: lakenakuru,
      type: "wellness retreats",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,000",
      oldPrice:"Kshs 4,400",
    },
    {
      image: lakenakuru,
      type: "Culinary tours",
      alt: "image of lake nakuru ",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptate explicabo obcaecati numquam quas!",
      linkText: "Read More",
      price: "Kshs 4,400",
      oldPrice:"Kshs 5,000",
    },
  ];